version: '3.8'
services:
  qdrant:
    container_name: qdrant
    environment: {}
    ports:
    - 6333:6333
    volumes: []
    image: qdrant/qdrant:latest
  ollama:
    container_name: ollama
    environment: {}
    ports:
    - 11434:11434
    volumes:
    - ./ollama_data:/root/.ollama
    image: ollama/ollama:latest
