[project]
name = "hyper-graph"
version = "0.1.0"
description = "HyperGraph Knowledge Ecosystem"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.26"]
build-backend = "uv_build"
